Filebrowser & Docs
GhostWriters/DockSTARTer pull request #1152
Opened 2020-10-14 23:29 UTC by angrycuban13

# Pull request

**Purpose**
Closes #1145 

**Approach**
How does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2020-10-20 13:58 UTC, nemchik requested changes

2020-10-20 13:58 UTC, nemchik commented on compose/.apps/filebrowser/filebrowser.yml
> +      - PUID=${PUID}
Does filebrowser actually use PUID/PGID?

(Note that I make it a habit to always pass TZ even if it's not used, but I don't do it with PUID/PGID).

2020-10-20 13:58 UTC, nemchik commented on compose/.apps/filebrowser/filebrowser.yml
> +      - FB_PORT=${FILEBROWSER_PORT_80}
What is the use case for allowing the port to be set differently inside the container? All I can think of is running the container in host network mode and wanting to change the port. Other than that I would say we should try to keep the app running on port 80 inside the container since it would be an expected port.

p.s. I think qbittorrent is the only app that breaks this rule because it REALLY hates when you set the port on the container without setting the port on the app itself, although that may have changed since it was added.

2020-10-20 13:58 UTC, nemchik commented on compose/.apps/filebrowser/filebrowser.ports.yml
> +      - ${FILEBROWSER_PORT_80}:${FILEBROWSER_PORT_80}
See port comments on the environment section.

2020-10-20 13:58 UTC, nemchik commented on compose/.apps/filebrowser/filebrowser.labels.yml
> +      com.dockstarter.appvars.filebrowser_share_dir: "~/.config/appdata/filebrowser"
```suggestion
      com.dockstarter.appvars.filebrowser_share_dir: "~/.config/appdata/filebrowser/share"
```
I think this should be a subdirectory to keep it separated from the actual config and not imply that it has to be the same folder as the config.

2020-10-21 13:20 UTC, angrycuban13 commented on compose/.apps/filebrowser/filebrowser.yml
> +      - PUID=${PUID}
I had it on my compose and I didn't have issues as far as I can tell.

I did check on Halian's compose and she passes PGID/PUID as the `user:` so something worth adding and removing this?

2020-10-21 13:23 UTC, angrycuban13 commented on compose/.apps/filebrowser/filebrowser.labels.yml
> +      com.dockstarter.appvars.filebrowser_share_dir: "~/.config/appdata/filebrowser"
Fair enough, I just filled that in so it wouldn't fail, but the end user needs to change it to the folder he wants to actually share anyways since that's the path that gets mounted to `/srv`

2020-10-21 17:52 UTC, nemchik commented on compose/.apps/filebrowser/filebrowser.yml
> +      - PUID=${PUID}
If the container runs without `user:` i would recommend avoiding it. Running without it means the container runs as root which gives it permissions it might not otherwise have, and for a file browser container I would probably thing having root permissions is a good thing.

2020-10-29 01:31 UTC, nemchik approved these changes

2020-10-29 01:40 UTC, merged