Adding jfa-go and docs
GhostWriters/DockSTARTer pull request #1196
Opened 2020-12-10 03:14 UTC by angrycuban13

# Pull request

**Purpose**
Closes #1186

2020-12-12 05:32 UTC, nemchik requested changes

2020-12-12 05:32 UTC, nemchik commented on compose/.apps/jfago/jfago.labels.yml
> +      com.dockstarter.appinfo.nicename: "jfa-go"
`nicename` has to be `jfago` or some variant with caps like `JFAgo` or something. has to match the var names.

2020-12-12 05:32 UTC, nemchik commented on compose/.apps/jfago/jfago.yml
> +      - PUID=${PUID}
doesn't look like this image uses PUID/PGID

2020-12-14 03:55 UTC, angrycuban13 commented on compose/.apps/jfago/jfago.yml
> +      - PUID=${PUID}
25c8e68

2020-12-14 03:56 UTC, angrycuban13 commented on compose/.apps/jfago/jfago.labels.yml
> +      com.dockstarter.appinfo.nicename: "jfa-go"
afb2186

2020-12-14 19:48 UTC, nemchik commented
Missing nav link here too 😄

2020-12-14 22:40 UTC, angrycuban13 commented
Oh no! Lol, fixed it in all 3.

2020-12-26 13:09 UTC, nemchik approved these changes

2020-12-26 13:41 UTC, merged