Adding LDAP-Auth & Docs
GhostWriters/DockSTARTer pull request #1197
Opened 2020-12-10 03:21 UTC by angrycuban13

# Pull request

**Purpose**
Closes #1173

2020-12-12 05:34 UTC, nemchik requested changes
Some files missing a blank newline as the last line also.

2020-12-12 05:34 UTC, nemchik commented on compose/.apps/ldapauth/ldapauth.yml
> +      - ${DOCKERSHAREDDIR}:/shared
don't include shared with new apps

2020-12-14 03:57 UTC, angrycuban13 commented on compose/.apps/ldapauth/ldapauth.yml
> +      - ${DOCKERSHAREDDIR}:/shared
e82356c

2020-12-14 19:47 UTC, nemchik commented
Some failing checks here:

- image issue? not sure what's up
- editorconfig: probably trailing newlines missing
- navigation link

2020-12-14 22:47 UTC, angrycuban13 commented
Yeah looks like my CTRL+F fucked some stuff up. Should be fixed now.

2020-12-26 13:10 UTC, nemchik approved these changes

2020-12-26 13:15 UTC, merged