Adding OpenLDAP & Docs
GhostWriters/DockSTARTer pull request #1198
Opened 2020-12-10 03:26 UTC by angrycuban13

# Pull request

Closes #1170

2020-12-12 05:35 UTC, nemchik requested changes

2020-12-12 05:35 UTC, nemchik commented on compose/.apps/openldap/openldap.yml
> +      - ${DOCKERSHAREDDIR}:/shared
don't include shared on new apps

2020-12-14 03:54 UTC, angrycuban13 commented on compose/.apps/openldap/openldap.yml
> +      - ${DOCKERSHAREDDIR}:/shared
576c187

2020-12-14 19:44 UTC, nemchik approved these changes

2020-12-14 19:45 UTC, nemchik commented
One failing check (navigation link in mkdocs) and I think we're good.

2020-12-22 00:31 UTC, nemchik requested changes

2020-12-22 00:31 UTC, nemchik commented on docs/apps/openldap.md
> +[![Docker Pulls](https://img.shields.io/docker/pulls/linuxserver/duplicati?style=flat-square&color=607D8B&label=docker%20pulls&logo=docker)](https://hub.docker.com/r/osixia/openldap/)
Duplicati?

2020-12-22 00:31 UTC, nemchik commented on docs/apps/openldap.md
> +[![GitHub Stars](https://img.shields.io/github/stars/linuxserver/docker-ombi?style=flat-square&color=607D8B&label=github%20stars&logo=github)](https://github.com/docker-openldap)
Ombi?

2020-12-23 02:35 UTC, angrycuban13 commented on docs/apps/openldap.md
> +[![Docker Pulls](https://img.shields.io/docker/pulls/linuxserver/duplicati?style=flat-square&color=607D8B&label=docker%20pulls&logo=docker)](https://hub.docker.com/r/osixia/openldap/)
Talk about a bad search and replace.... 8760ab0

2020-12-26 13:11 UTC, nemchik approved these changes

2020-12-26 13:11 UTC, merged