Update issue templates
GhostWriters/DockSTARTer pull request #1215
Opened 2020-12-28 20:48 UTC by angrycuban13

2021-01-03 15:03 UTC, nemchik requested changes

2021-01-03 15:03 UTC, nemchik commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: ''
What does title do?

2021-01-03 15:03 UTC, nemchik commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
This can probable use the `bug` label.

2021-01-03 15:03 UTC, nemchik commented on .github/ISSUE_TEMPLATE/feature-request.md
> +labels: ''
This can probably use the `enhancement` label

2021-01-03 15:12 UTC, angrycuban13 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: ''
I have no idea lol. I think if we wanted a specific title like `[BUG] Blah blah blah`

2021-01-03 15:38 UTC, angrycuban13 commented on .github/ISSUE_TEMPLATE/feature-request.md
> +labels: ''
1299787

2021-01-03 15:38 UTC, angrycuban13 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
1299787

2021-01-03 15:38 UTC, angrycuban13 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: ''
1299787

2021-01-10 01:34 UTC, nemchik approved these changes

2021-01-10 02:24 UTC, merged