Adding '## Install/Setup' to all docs
GhostWriters/DockSTARTer pull request #1219
Opened 2021-01-02 15:38 UTC by angrycuban13

# Pull request

**Purpose**
Standardization of documentation.

2021-01-10 01:36 UTC, nemchik commented
We have more than 83, do some already have this?

2021-01-10 02:15 UTC, angrycuban13 commented
> We have more than 83, do some already have this?

Yeah you actually started doing it for some a while back.

2021-01-10 02:23 UTC, angrycuban13 commented
9e991fa is where it started

2021-01-10 02:34 UTC, nemchik commented
So, many of these don't actually have anything in the newly added section. Should we come up with something generic? Or have some kind of placeholder?

2021-01-10 02:41 UTC, angrycuban13 commented
> So, many of these don't actually have anything in the newly added section. Should we come up with something generic? Or have some kind of placeholder?

Hmmm not sure, I figured we could just leave it empty and that way if we need to add anything related to Install or Setup the header is already there.

2021-01-10 14:32 UTC, nemchik commented
I like having the structure, but I don't want to leave it empty. I think having a universal placeholder would be good. It would allow for mass search/replace, and it'll look less awkward on the pages in mkdocs.

2021-01-10 16:43 UTC, angrycuban13 commented
What are you thinking of as the universal placeholder? Some pages already do have the `Install\Setup` with instructions by the way

2021-01-19 13:59 UTC, nemchik commented
> What are you thinking of as the universal placeholder? Some pages already do have the `Install\Setup` with instructions by the way

Maybe something like

> This application does not have any specific setup instructions documented. If you need assistance setting up this application please visit our [support page](https://dockstarter.com/basics/support/).

2021-01-22 00:17 UTC, angrycuban13 commented
> This application does not have any specific setup instructions documented. If you need assistance setting up this application please visit our [support page](https://dockstarter.com/basics/support/).

Would this be ideal or do you want something else?
```md
## Install/Setup
This application does not have any specific setup instructions documented. If you need assistance setting up this application please visit our support page.
```

2021-01-22 00:47 UTC, angrycuban13 commented
Closes #1244

2021-01-24 18:45 UTC, nemchik requested changes

2021-01-24 18:45 UTC, nemchik commented on docs/apps/bitwarden.md
> +sudo chown -R $USER:$GROUP ~/.config/appdata/bitwarden
```suggestion
sudo chown -R $USER:$USER ~/.config/appdata/bitwarden
```
There is no such built-in variable as `$GROUP` but 99% of the time the group is named after the user.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/grafana.md
> +sudo chown -R $USER:$GROUP ~/.config/appdata/grafana
```suggestion
sudo chown -R $USER:$USER ~/.config/appdata/grafana
```
There is no such built-in variable as `$GROUP` but 99% of the time the group is named after the user.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/grafana.md
> +```
```suggestion
> mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied, GF_PATHS_DATA='/var/lib/grafana' is not writable.
```
This should be kept a quote. It's not bash code or commands. It's output.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/plex.md
> +    - /dev/dri:/dev/dri
```suggestion
  plex:
    devices:
      - /dev/dri:/dev/dri
```
These need to stay indented so that users can directly copy/paste from here.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/plex.md
> +```
90% sure the word wrapping here will break yaml. Also the original indentation allows direct copy/paste into override files. This edit removes the indentation.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/tdarr.md
> +```bash
This isn't bash, and not code meant to be run. Possibly just quote instead of codeblock?

2021-01-24 18:45 UTC, nemchik commented on docs/apps/tdarr.md
> +sudo chown -R $USER:$GROUP /path/to/location
```suggestion
sudo chown -R $USER:$USER /path/to/location
```
There is no such built-in variable as `$GROUP` but 99% of the time the group is named after the user.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/xbackbone.md
> +sudo chown -R $USER:$GROUP ~/.config/appdata/xbackbone/
```suggestion
sudo chown -R $USER:$USER ~/.config/appdata/xbackbone/
```
There is no such built-in variable as `$GROUP` but 99% of the time the group is named after the user.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/watchtower.md
> +    - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-server-1
Removing indentation means end users can't copy directly into override files. They will have to manually add indentation.

2021-01-24 18:45 UTC, nemchik commented on docs/apps/watchtower.md
> +    - WATCHTOWER_NOTIFICATIONS=email
Removing indentation means end users can't copy directly into override files. They will have to manually add indentation.

2021-01-24 19:29 UTC, angrycuban13 commented on docs/apps/plex.md
> +    - /dev/dri:/dev/dri
This was definitely that stupid ass bot

2021-01-24 19:29 UTC, angrycuban13 commented on docs/apps/watchtower.md
> +    - WATCHTOWER_NOTIFICATIONS=email
Stupid bot

2021-01-24 19:35 UTC, angrycuban13 commented on docs/apps/watchtower.md
> +    - WATCHTOWER_NOTIFICATIONS=email
6573ab2

2021-01-24 19:36 UTC, angrycuban13 commented on docs/apps/watchtower.md
> +    - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-server-1
6573ab2

2021-01-24 19:36 UTC, angrycuban13 commented on docs/apps/tdarr.md
> +```bash
6573ab2

2021-01-24 19:37 UTC, angrycuban13 commented on docs/apps/plex.md
> +```
16f3883

2021-01-24 22:30 UTC, nemchik requested changes

2021-01-24 22:30 UTC, nemchik commented on docs/apps/homeassistant.md
> +  - PYTHONWARNINGS="ignore:Unverified HTTPS request"
```suggestion
    environment:
      - PYTHONWARNINGS="ignore:Unverified HTTPS request"
```

2021-01-24 22:30 UTC, nemchik commented on docs/apps/nextcloud.md
> +```
```suggestion
> Performance warning You chose SQLite as database. SQLite should only be used for minimal and development instances. For production we recommend a different database backend. If you use clients for file syncing, the use of SQLite is highly discouraged.
```
This isn't code, just a message that may be shown.

2021-01-24 22:30 UTC, nemchik commented on docs/apps/speedtest.md
> +order to use this container._
Nothing to resolve here, just commenting that I hate that you can have italics across multiple lines in this way. It makes no sense and is ugly as hell. It does work, so it's ok to merge.

2021-01-24 23:26 UTC, angrycuban13 commented on docs/apps/nextcloud.md
> +```
Yeah but it's an HTML message :( syntax is right God damn it! Lol. I'll fix it

2021-01-24 23:27 UTC, angrycuban13 commented on docs/apps/homeassistant.md
> +  - PYTHONWARNINGS="ignore:Unverified HTTPS request"
I'll need to review every page now just in case

2021-01-25 02:41 UTC, angrycuban13 commented on docs/apps/speedtest.md
> +order to use this container._
ca8b971

2021-02-07 00:49 UTC, nemchik approved these changes

2021-02-07 00:53 UTC, merged