Adding Wireguard and Docs
GhostWriters/DockSTARTer pull request #1222
Opened 2021-01-02 20:06 UTC by angrycuban13

# Pull request

**Purpose**
Addresses #431

2021-01-10 14:34 UTC, nemchik requested changes

2021-01-10 14:34 UTC, nemchik commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
Would it make sense to just reuse the `wireguard_port_51820` variable?

2021-01-10 14:34 UTC, nemchik commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_internal_subnet: "10.13.13.0"
Where did this default value come from? (just asking)

2021-01-10 14:34 UTC, nemchik commented on compose/.apps/wireguard/wireguard.yml
> +    environment:
Sort alphabetically.

2021-01-10 16:44 UTC, angrycuban13 commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_internal_subnet: "10.13.13.0"
LSIO

2021-01-10 16:49 UTC, angrycuban13 commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
From when I set up Wireguard on the USG the server port is unique to Wireguard. Not sure why LSIO has both a variable for it and a port. The guy I had test it said it worked fine the way it is though.

2021-01-10 20:35 UTC, nemchik commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
I assume you can change the port for the app on the inside of the container. Qbittorrent or the VPN variant is setup for this as well. I think we can just use one variable instead of two. The environment and ports will need to be adjusted in the templates.

2021-01-10 22:30 UTC, angrycuban13 commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
So then just have `com.dockstarter.appvars.wireguard_server_port_51820` and reference that variable in both the `ports.yml` and `wireguard.yml`

2021-01-10 22:31 UTC, angrycuban13 commented on compose/.apps/wireguard/wireguard.yml
> +    environment:
what's not sorted alphabetically?

2021-01-10 22:36 UTC, angrycuban13 commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
8beb4b0 addresses this change, let me know if that's what you had in mind.

2021-01-24 17:20 UTC, nemchik requested changes

2021-01-24 17:20 UTC, nemchik commented on compose/.apps/wireguard/wireguard.yml
> +      - ALLOWEDIPS=${WIREGUARD_ALLOWED_IPS}
```suggestion
    environment:
      - ALLOWEDIPS=${WIREGUARD_ALLOWED_IPS}
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET}
      - PEERDNS=${WIREGUARD_PEER_DNS}
      - PEERS=${WIREGUARD_PEERS}
      - PGID=${PGID}
      - PUID=${PUID}
      - SERVERPORT=${WIREGUARD_SERVER_PORT_51820}
      - SERVERURL=${WIREGUARD_SERVER_URL}
      - TZ=${TZ}
```
Sorted

2021-01-24 17:20 UTC, nemchik commented on compose/.apps/wireguard/wireguard.yml
> +    environment:
Replacing with new comment.

2021-01-24 17:20 UTC, nemchik commented on compose/.apps/wireguard/wireguard.yml
> +      - net.ipv4.conf.all.src_valid_mark=1
```suggestion
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /lib/modules:/lib/modules
      - ${DOCKERCONFDIR}/wireguard:/config
      - ${DOCKERSTORAGEDIR}:/storage
```
Just moving `sysctls` above `volumes`

2021-01-24 17:22 UTC, nemchik requested changes

2021-01-24 17:22 UTC, nemchik commented on compose/.apps/wireguard/wireguard.ports.yml
> +      - ${WIREGUARD_SERVER_PORT_51820}:51820/udp
```suggestion
      - ${WIREGUARD_SERVER_PORT_51820}:${WIREGUARD_SERVER_PORT_51820}/udp
```

2021-01-24 17:23 UTC, nemchik commented on compose/.apps/wireguard/wireguard.labels.yml
> +      com.dockstarter.appvars.wireguard_server_port: "51820"
https://github.com/GhostWriters/DockSTARTer/pull/1222#discussion_r563322866 this resolves what I'm talking about. If you can change the port the app runs on from inside the container you need to be able to assign the compose template to that port for the inside of the container as well.

2021-01-24 18:50 UTC, nemchik approved these changes

2021-01-24 19:34 UTC, merged