Adding PlexAniSync & Docs
GhostWriters/DockSTARTer pull request #1225
Opened 2021-01-02 23:27 UTC by angrycuban13

# Pull request

**Purpose**
Closes #1224

2021-01-10 01:43 UTC, nemchik commented
Aarch64 can use the armv7l image, but it needs a file in the compose template folder.

2021-01-10 02:39 UTC, nemchik requested changes

2021-01-10 02:39 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.yml
> +    environment:
Sort these please.

2021-01-10 02:39 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.labels.yml
> +      com.dockstarter.appvars.plex_anisync_ani_username: ""
Underscore on this one, but not the rest?

2021-01-10 02:49 UTC, angrycuban13 commented on compose/.apps/plexanisync/plexanisync.yml
> +    environment:
I was trying to put them alphabetically, do you want `command` under `container_name`?

2021-01-10 02:50 UTC, angrycuban13 commented on compose/.apps/plexanisync/plexanisync.labels.yml
> +      com.dockstarter.appvars.plex_anisync_ani_username: ""
Fixed on 0e3231d

2021-01-10 14:36 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.yml
> +    environment:
The environment variables.

2021-01-10 14:44 UTC, nemchik requested changes

2021-01-10 14:44 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.labels.yml
> +      com.dockstarter.appvars.plexanisync_interval: "3600"
```suggestion
      com.dockstarter.appinfo.deprecated: "false"
      com.dockstarter.appinfo.description: "Sync anime watched status from Plex to AniList"
      com.dockstarter.appinfo.nicename: "Plexanisync"
      com.dockstarter.appvars.plexanisync_ani_token: ""
      com.dockstarter.appvars.plexanisync_ani_username: ""
      com.dockstarter.appvars.plexanisync_enabled: "false"
      com.dockstarter.appvars.plexanisync_interval: "3600"
      com.dockstarter.appvars.plexanisync_network_mode: ""
      com.dockstarter.appvars.plexanisync_plex_section: "Anime"
      com.dockstarter.appvars.plexanisync_plex_token: ""
      com.dockstarter.appvars.plexanisync_plex_url: "http://plex:32400"
```
Sorted

2021-01-10 14:44 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.x86_64.yml
> +    image: rickdb/plexanisync:latest
```suggestion
    image: rickdb/plexanisync
```

2021-01-10 14:44 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.yml
> +      - INTERVAL=${PLEXANISYNC_INTERVAL}
```suggestion
      - ANI_TOKEN=${PLEXANISYNC_ANI_TOKEN}
      - ANI_USERNAME=${PLEX_ANISYNC_ANI_USERNAME}
      - INTERVAL=${PLEXANISYNC_INTERVAL}
      - PGID=${PGID}
      - PLEX_SECTION=${PLEXANISYNC_PLEX_SECTION}
      - PLEX_TOKEN=${PLEXANISYNC_PLEX_TOKEN}
      - PLEX_URL=${PLEXANISYNC_PLEX_URL}
      - PUID=${PUID}
      - TZ=${TZ}
```

2021-01-10 14:44 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.yml
> +    environment:
Added a review suggestion for it.

2021-01-10 22:37 UTC, angrycuban13 commented on compose/.apps/plexanisync/plexanisync.x86_64.yml
> +    image: rickdb/plexanisync:latest
This is weird, looks like my commits didn't push last night

2021-01-24 17:17 UTC, nemchik requested changes

2021-01-24 17:17 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.aarch64.yml
> +  plex:
```suggestion
  plexanisync:
```

2021-01-24 17:17 UTC, nemchik commented on compose/.apps/plexanisync/plexanisync.yml
> +      - ANI_USERNAME=${PLEX_ANISYNC_ANI_USERNAME}
```suggestion
      - ANI_USERNAME=${PLEXANISYNC_ANI_USERNAME}
```

2021-01-24 18:52 UTC, nemchik approved these changes

2021-01-24 19:44 UTC, merged