Fixes YoutubeDL
GhostWriters/DockSTARTer pull request #1239
Opened 2021-01-16 20:36 UTC by angrycuban13

# Pull request

**Purpose**
Closes #1236 

**Approach**
Adds the following enviroment variable:
```yml
    environment:
      - YDL_CONFIG_PATH=/config
```
to create a config file located in 
```yml
    volumes:
      - ${DOCKERCONFDIR}/youtube-dl/config:/config
```
which can then be used by the user to specify `youtube-dl` specific settings . For instance
```yml
ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: True    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/storage/downloads/youtube-dl/playlists/%(playlist_title)s/%(title)s [%(id)s].%(ext)s' # Playlist output directory
  update_poll_delay_min: 1440 # Automatically check for updates every 24h

ydl_options:  # youtube-dl options
  output: '/storage/downloads/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  age-limit: 6 # minimal age requirement / parental control setting
```

2021-01-24 17:00 UTC, nemchik commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
Do we need (both)
```yaml
      - ${DOCKERCONFDIR}/youtubedl:/youtube-dl
      - ${DOCKERCONFDIR}/youtube-dl/config:/config
```
or can we just do (replace the two above with just this one)
```yaml
      - ${DOCKERCONFDIR}/youtubedl:/config
```

2021-01-24 17:15 UTC, angrycuban13 commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
So we *need* `youtube-dl` as that's where the container data is but I imagine we can set the environment variable to point to `/youtube-dl` instead. Let me test it

2021-01-24 18:54 UTC, nemchik commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
What is the difference between config and data? What gets stored in each?

2021-01-24 19:17 UTC, angrycuban13 commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
`/config` is just something I chose to put the config file. You can make that whatever you want. 

If you go back to the issue on his repo there were like 3 diff methods to work with the config file and I chose the one that would work "BEST" with how we have DS structured.

2021-01-25 02:55 UTC, angrycuban13 commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
I just tested the following:
```yml
  youtube-dl:
    container_name: youtube-dl
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - YDL_CONFIG_PATH=/youtube-dl
    hostname: ${DOCKERHOSTNAME}
    image: nbr23/youtube-dl-server
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8083:8080
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/youtube-dl:/youtube-dl
      - ${DOCKERSTORAGEDIR}:/storage
```
I had a `config.yml` in `${DOCKERCONFDIR}/youtube-dl` that looked as follows:
```yml
ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: True    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/storage/downloads/youtube-dl/playlists/%(playlist_title)s/%(title)s [%(id)s].%(ext)s' # Playlist output directory
  update_poll_delay_min: 1440 # Automatically check for updates every 24h

ydl_options:  # youtube-dl options
  output: '/storage/downloads/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  age-limit: 6 # minimal age requirement / parental control setting
```
This **did not** work. The YouTube video still downloaded to `/youtube-dl` rather than `/storage/downloads/youtube-dl` as this tells it to ` output: '/storage/downloads/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory`

2021-01-25 15:17 UTC, nemchik requested changes

2021-01-25 15:17 UTC, nemchik commented on compose/.apps/youtubedl/youtubedl.labels.yml
> +      com.dockstarter.appvars.youtubedl_config_path: "/config"
```suggestion
      com.dockstarter.appvars.youtubedl_config_path: "/youtube-dl/config.yml"
```

2021-01-25 15:17 UTC, nemchik commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
```suggestion
      - ${DOCKERCONFDIR}/youtubedl:/youtube-dl
```

2021-01-27 00:10 UTC, angrycuban13 commented on compose/.apps/youtubedl/youtubedl.yml
> +      - ${DOCKERCONFDIR}/youtube-dl/config:/config
559b528

2021-01-27 00:10 UTC, angrycuban13 commented on compose/.apps/youtubedl/youtubedl.labels.yml
> +      com.dockstarter.appvars.youtubedl_config_path: "/config"
559b528

2021-01-27 04:03 UTC, nemchik approved these changes

2021-01-27 04:03 UTC, merged