Overrides for Petio
GhostWriters/DockSTARTer pull request #1301
Opened 2021-03-20 15:21 UTC by TRaSH-

Overrides for Petio thnx to mouzzampk2014

# Pull request

**Purpose**
Added Override for Petio

**Approach**
Added Override for Petio

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2021-03-20 15:44 UTC, angrycuban13 requested changes

2021-03-20 15:44 UTC, angrycuban13 commented on docs/overrides/petio.md
> +[petio](https://petio.tv/) is a third party companion app available to Plex server owners to allow their users to request, review and discover content. The app is built to appear instantly familiar a
Capitalize Petio

2021-03-20 15:44 UTC, angrycuban13 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
This line isn't really needed. I think Hotio added it for a reason but he directs you to read the docs. It won't really apply to the majority of users in my experience

2021-03-20 15:53 UTC, TRaSH- commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
the confdir ?
are you sure

2021-03-20 16:23 UTC, angrycuban13 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
The one where the database lives is actually the line below. 

```The folder /data/configdb isn't always required, take a look at the Mongo documentation to see if this applies to you.```

https://hotio.dev/containers/petio/

I think it would create less confusion for users if we don't include it but up to you. Especially since Hotio is directing them to create the folders *beforehand*.

2021-03-20 16:42 UTC, mouzzampk2014 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
I think this whole override could be more simple. I just posted it in a hurry so people will take advantage of petio. 

As all our apps include config directory so might be ideal to keep it when we add in the main repo but for override I think its better to remove the configdb. 

We need to add :rw to give permissions to folder otherwise users need to first create a folder and then set permission and then run image but adding :rw to config will avoid the steps.

2021-03-20 16:45 UTC, TRaSH- commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
i think personally we should just add it, this way when you got users that actually RTFM they come over and complain we're missing something.

2021-03-20 16:56 UTC, nemchik commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
The mongo folder should be inside the petio config folder

2021-03-20 16:59 UTC, nemchik commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
Ignore me. I didn't read the whole thing.

2021-03-20 16:59 UTC, TRaSH- commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
so something like this ?

```yml
  mongo:
    image: mongo
    hostname: ${DOCKERHOSTNAME}
    container_name: mongo
    user: "1000:1000"
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/petio/mongo:/data/configdb
      - ${DOCKERCONFDIR}/petio/mongo/db:/data/db
```

2021-03-20 17:05 UTC, TRaSH- commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
> Ignore me. I didn't read the whole thing.

to late it already happened

2021-03-20 17:07 UTC, HalianElf commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
Shouldn't it have `user: "${PUID}:${PGID}"` instead of 1000:1000?

2021-03-20 18:07 UTC, angrycuban13 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
Yep

2021-03-20 18:07 UTC, angrycuban13 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
> Ignore me. I didn't read the whole thing.

Ignored

2021-03-20 18:07 UTC, angrycuban13 commented
I'll sit on a computer and take a look in a min.

2021-03-20 18:16 UTC, angrycuban13 commented on docs/overrides/petio.md
> +      - ${DOCKERCONFDIR}/mongo:/data/configdb
So per Mongo's [documentation](https://docs.mongodb.com/manual/reference/configuration-options/#configuration-file) 

```You can configure mongod and mongos instances at startup using a configuration file. The configuration file contains settings that are equivalent to the mongod and mongos command-line options.```

I think this is more advanced usage of Mongo than our average users. It might just create confusion but I don't care if it gets merged with this line.

2021-03-20 18:19 UTC, angrycuban13 reviewed
Petio also supports

```yml
user: ${PUID}:${PGID}
```

@nemchik should we move away from environment variables if the `user` option is supported?

2021-03-20 18:19 UTC, angrycuban13 commented on docs/overrides/petio.md
> +    user: "1000:1000"
Change to

`user: ${PUID}:${PGID}`

2021-03-21 17:57 UTC, angrycuban13 approved these changes

2021-03-21 17:57 UTC, merged