Remove Flood options from rtorrentvpn
GhostWriters/DockSTARTer pull request #1342
Opened 2021-06-28 21:58 UTC by BanditTech

# Pull request

**Purpose**
remove flood options from rtorrentvpn

**Approach**
it fixes it with code!

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2021-07-25 20:07 UTC, nemchik commented
It makes sense to remove the flood options, but I wasn't sure about the rest of the changes. The strict port option didn't seem necessary, but I'm fine including it. We should include it in the other VPN downloader images (the ones with VPN in the name) as well.

I think the ports were included as they seemed standard and necessary for tTorrent, but I'm not against removing them if they aren't needed.

Keep in mind, we would need to remove these things in multiple places. Mainly the labels file, ports file, and the main file (named for the app) environment section.

2021-07-25 20:25 UTC, BanditTech commented
I just included it because I thought it was a new setting, but after looking further I think you are right. It is not really required for most people.

Mostly it would just be removing the stale settings which are no longer present in the image. 

But after testing the different torrent downloaders and their GUI, this just feels a bit old and clunky compared to qBitTorrent. So I would not recommend anyone to use this in a new install compared to qBit... With so many choices of downloaders, for new people it might be better to just remove some of the poorer choices IMO.

2021-07-25 20:30 UTC, BanditTech commented
the files edited so far are inside the .app folder, the three you mentioned I thought I did. Did I miss something?

2021-07-25 20:31 UTC, BanditTech commented
the old ports were for the flood client, which is no longer packaged in this image

2021-07-25 20:33 UTC, nemchik commented
I don't think this image is broken, but there do seem to be some deprecated options (flood) still lingering in our template.

As for including it in DS, the goal has never been to limit what options users have. Letting users choose what to run is a bit of a core goal of the project. I personally agree qbit is better, but if someone wants to run something else, it's up to them.

2021-07-25 20:44 UTC, BanditTech commented
That is true, its good to give choices. 
It is just unfortunate that the best torrent option shows up after every single other worse choice on the list, and there are several.

2021-07-27 12:08 UTC, nemchik commented
> That is true, its good to give choices.
> It is just unfortunate that the best torrent option shows up after every single other worse choice on the list, and there are several.

Yeah, it's just alphabetical. I'll submit a proper review with inline comments for anything else this needs.

2021-07-27 12:18 UTC, nemchik requested changes

2021-07-27 12:18 UTC, nemchik commented on compose/.apps/rtorrentvpn/rtorrentvpn.yml
> +      - STRICT_PORT_FORWARD=${RTORRENTVPN_STRICT_PORT_FORWARD}
Let's skip adding the strict variable. Removing the flood variable is fine.

2021-07-27 12:18 UTC, nemchik commented on compose/.apps/rtorrentvpn/rtorrentvpn.labels.yml
>        com.dockstarter.appvars.rtorrentvpn_port_3000: "3000"
Let's remove the 3 unused ports from this file as well.

2021-07-27 12:18 UTC, nemchik commented on compose/.apps/rtorrentvpn/rtorrentvpn.labels.yml
> +      com.dockstarter.appvars.rtorrentvpn_strict_port_forward: "yes"
Let's not add the strict variable in this PR. We could consider adding it to all the VPN download client containers in a separate pr.

2021-07-29 03:51 UTC, BanditTech commented on compose/.apps/rtorrentvpn/rtorrentvpn.yml
> +      - STRICT_PORT_FORWARD=${RTORRENTVPN_STRICT_PORT_FORWARD}
thats a good idea

2021-07-29 03:53 UTC, BanditTech commented
OK, sorry for the delay, I have been a little preoccupied. Thank you for the notes, I followed them and feel its ready for merge now.

2021-11-15 15:29 UTC, nemchik commented
I need to have another look at this.

2023-02-26 15:40 UTC, nemchik commented
Awkward timing, binhex deprecated the image a few days ago https://github.com/binhex/arch-rtorrentvpn/commit/98351f05c07600691c30a99473ccf3475c5b5121

I believe `51413` and `6881` are meant for incoming connections, and not documented by binhex.

Aside from that, I believe your changes are correct, so I'm going to merge them, but I think we will likely mark this app as deprecated in the future.

2023-02-26 15:41 UTC, nemchik approved these changes

2023-02-26 15:42 UTC, merged