Update thelounge.md
GhostWriters/DockSTARTer pull request #1347
Opened 2021-07-09 14:36 UTC by BanditTech

# Pull request

**Purpose**
Describe the problem or feature in addition to a link to the issues.

**Approach**
How does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2021-07-10 12:05 UTC, TRaSH- approved these changes

2021-07-10 12:32 UTC, angrycuban13 submitted a review, later dismissed

2021-07-10 12:32 UTC, angrycuban13 commented on docs/apps/thelounge.md
> +* Now from the host, edit `/config/config.js`, wherever you've mapped it
Change this line to point to `~/.config/appdata/thelounge/` as most people using DS will have this path.

2021-07-10 12:32 UTC, angrycuban13 commented on docs/apps/thelounge.md
> +* `docker exec -it thelounge s6-setuidgid abc thelounge add <user>`
Why is this necessary? I don't recall having to do any of this when I ran thelounge.

2021-07-10 12:32 UTC, angrycuban13 commented on docs/apps/thelounge.md
> +* To log in to the application, browse to `http://<hostip>:9100` or `http://<container>:9000`
> `http://<container>:9000`

Unless you are using `macvlan` you will not be able to access a container's Web UI by using the container name as your host will not know what IP to map `thelounge` to.

2021-07-10 21:47 UTC, BanditTech commented on docs/apps/thelounge.md
> +* `docker exec -it thelounge s6-setuidgid abc thelounge add <user>`
If you do not enable this option, the connection is not persistant. It will disconnect as soon as you close the browser, since each person using the service is considered a guest account.

2021-07-10 21:48 UTC, BanditTech commented on docs/apps/thelounge.md
> +* To log in to the application, browse to `http://<hostip>:9100` or `http://<container>:9000`
I merely wanted to provide some information regarding the port being different in the container or the host, since the script automatically changes it to 9100 from 9000.

2021-07-10 21:49 UTC, BanditTech commented on docs/apps/thelounge.md
> +* To log in to the application, browse to `http://<hostip>:9100` or `http://<container>:9000`
with organizer for example, I am using `http://<container>:9000`

2021-07-11 00:27 UTC, angrycuban13 commented on docs/apps/thelounge.md
> +* To log in to the application, browse to `http://<hostip>:9100` or `http://<container>:9000`
Right because Organizr is in the same network as TheLounge.

2021-07-11 17:30 UTC, nemchik requested changes
Originally the port was set to `9100` to prevent a potential conflict with portainer, since portainer used to be enabled by default. At this point, I feel like users learning to understand and handle port conflicts is a required growing pain and we should change https://github.com/GhostWriters/DockSTARTer/blob/1f209a453d0932de7c9f49bd08241407c67ed35c/compose/.apps/thelounge/thelounge.labels.yml#L9 to use port `9000` and adjust the documentation here to match

2021-07-11 17:30 UTC, nemchik commented on docs/apps/thelounge.md
> +* To log in to the application, browse to `http://<hostip>:9100`
```suggestion
* To log in to the application, browse to `http://<hostip>:9000`
```

2021-07-11 17:30 UTC, nemchik commented on docs/apps/thelounge.md
> +* Through organizr you would use `http://<container>:9000`
```suggestion
* Other containerized applications such as organizr would use `http://<container>:9000`
```

2021-07-11 20:47 UTC, BanditTech commented
OK, the template file is edited to match the documentation.

2021-07-11 23:11 UTC, nemchik approved these changes

2021-07-25 12:51 UTC, merged