Add Homebridge
GhostWriters/DockSTARTer pull request #1421
Opened 2022-01-22 19:33 UTC by dragonandy

# Pull request

**Purpose**
Add Homebridge as a new application

**Approach**
Add Homebridge 

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
add Homebridge  application
add Homebridge  docs
tested on my own machine and works fine

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2022-01-22 21:04 UTC, nemchik requested changes

2022-01-22 21:04 UTC, nemchik commented on compose/.apps/homebridge/homebridge.hostname.yml
> +  homeassistant:
Wrong name :)

2022-01-22 21:04 UTC, nemchik commented on compose/.apps/homebridge/homebridge.yml
> +      - ENABLE_AVAHI=0
Please sort these alphabetically. Also may as well make them all use variables.

2022-01-22 21:04 UTC, nemchik commented on compose/.apps/homebridge/homebridge.aarch64.yml
> +    image: oznu/homebridge:ubuntu
Any particular reason for using the Ubuntu tag instead of the latest tag?

2022-01-23 06:08 UTC, dragonandy commented on compose/.apps/homebridge/homebridge.aarch64.yml
> +    image: oznu/homebridge:ubuntu
This application use ubuntu based image to work better with some plugins. some plugin dont like alpine enviroment, furthermore alpine is not notably smaller than the ubuntu one.

2022-01-23 06:10 UTC, dragonandy commented on compose/.apps/homebridge/homebridge.aarch64.yml
> +    image: oznu/homebridge:ubuntu
This application use ubuntu based image to work better with some plugins. The latest tag one is using alpine based image, but some plugin don't like the alpine enviroment, furthermore alpine is not notably smaller than the ubuntu one.

2022-01-23 06:14 UTC, dragonandy commented on compose/.apps/homebridge/homebridge.hostname.yml
> +  homeassistant:
thats a problem :(

2022-01-23 06:40 UTC, dragonandy commented
I cleanup those problems, and force pushed two new commits. please do another round of review

2022-01-24 13:56 UTC, nemchik approved these changes
LGTM, thanks!

2022-01-24 13:57 UTC, nemchik commented
Actually, I'm just now looking at the checks and it seems like there's some trailing whitespace issues, and we need a link added to the mkdocs.yml in the top of the repo.

2022-04-02 20:24 UTC, angrycuban13 commented
@dragonandy 

1. You need to fix whitespace in the following lines.
- 	9: Trailing whitespace
- 	10: Trailing whitespace
- 	11: Trailing whitespace

2. You need to add `homebridge.md` in `mkdocs.yml`

2023-02-19 00:08 UTC, closed without merging