Including CONTRIBUTING.md write-ups for setting up your dev environment and adding a new app
GhostWriters/DockSTARTer pull request #1491
Opened 2022-06-23 04:06 UTC by shahvirb

# Pull request

**Purpose**
Let's streamline contributions. When I added "homer" app support recently in PR #1489 I had to learn how to setup my dev environment and then how to a add new app. I want to document the process to help others.

**Open Questions and Pre-Merge TODOs**
- [ ] Is there anything more you do in "setting up your dev environment"?
- [ ] Feel free to suggest additional manual test cases under "Adding an App"

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2022-06-23 12:59 UTC, nemchik commented
I like the direction this is going, but I have a few things I'd like to see done differently. I'll add a full review in the near future.

2022-06-24 03:45 UTC, shahvirb commented
Added a section on markdown files to cover the linting rules since my first commit failed markdownlint.
https://github.com/GhostWriters/DockSTARTer/pull/1491/commits/48e51bddb1875a10b4b1f22398f16ef15894d72f

2022-06-29 14:51 UTC, nemchik requested changes

2022-06-29 14:51 UTC, nemchik commented on .github/CONTRIBUTING.md
> +We use [GitHub Actions](https://github.com/GhostWriters/DockSTARTer/actions) to run [tests](https://github.com/GhostWriters/DockSTARTer/tree/master/.github/workflows) on the code in the repository. C
```suggestion
We use [GitHub Actions](https://github.com/GhostWriters/DockSTARTer/actions) to run [checks](https://github.com/GhostWriters/DockSTARTer/tree/master/.github/workflows) on the code in the repository. Code must pass checks run by GitHub Actions in order to merge to the `master` branch of the repository.
```

2022-06-29 14:51 UTC, nemchik commented on .github/CONTRIBUTING.md
> +You should now have an environment where the DockSTARTer GUI and CLI use files you are editing in your local git repository. Eg. if you add a new app into `/path/to/your/ds-repo/compose/.apps` you sh
I'm not sure about this section. The symlink steps feel unnecessary.

Typically when I am doing development for DS, I will do something along these lines:
```shell
# fork the repo on github
cd ~/.docker
git status # good practice to check
git pull # make sure I have the latest commits
git remote -v # review remotes
git remote add <my_fork_name> <my_fork_url> # only needed once
git checkout -b <my_branch_name> # make a new branch to make my changes in
# make my changes
# test my changes, ex: run the new app, or ensure the shell script changes work and run `ds -t <function>` on any changed functions
git commit -m "<describe_changes>"
git push -u <my_fork_name> <my_branch_name>
# open a PR
# others can test by adding my remote and running `ds -u <my_fork_name>/<my_branch_name>`
```
(my personal process is slightly different since I have write perms in this repo and do not use a fork, but I still always do a branch and PR my own work)

A concern with the symlink approach described would be if a user completes the listed steps (doing the linked directories) and then runs `ds -u` it would pull in whatever is in master from this repo, which would then overwrite any changes in the separately cloned folder.

I am open to hearing other options for how this can be made as easy as possible to encourage contributors.

2022-06-29 22:58 UTC, shahvirb commented on .github/CONTRIBUTING.md
> +You should now have an environment where the DockSTARTer GUI and CLI use files you are editing in your local git repository. Eg. if you add a new app into `/path/to/your/ds-repo/compose/.apps` you sh
> A concern with the symlink approach described would be if a user completes the listed steps (doing the linked directories) and then runs ds -u it would pull in whatever is in master from this repo, which would then overwrite any changes in the separately cloned folder.

Yes good point.

Thanks for outlining your git process however git aside what I was seeking to explain here is how we can use a git repo as _the app_. 
> test my changes, ex: run the new app,
Can you elaborate on this? You're saying just invoke main.sh from the git repo itself?

2022-06-29 23:47 UTC, nemchik commented on .github/CONTRIBUTING.md
> +You should now have an environment where the DockSTARTer GUI and CLI use files you are editing in your local git repository. Eg. if you add a new app into `/path/to/your/ds-repo/compose/.apps` you sh
> I was seeking to explain here is how we can use a git repo as _the app_.

Yes. Actually when you install DS with the standard instructions what is happening is the `main.sh` is loaded into memory and it detects if you have DS installed. If you do not have it installed, it clones the repo to the standard directory `~/.docker` and then runs itself from there using `~/.docker/main.sh`. If you already have DS installed (detected via the `ds` symlink) whether it's in the default location or any other folder you chose to clone the repo into, it'll run DS from there. Point is, any installation of DS is actually cloning the repo and running from the repo (and it can be cloned to any folder you like). Once cloned, you can run `bash /path/to/ds/main.sh` and it will setup a symlink so that you can just run `ds` in the future and it'll execute `main.sh` from wherever the repo is cloned.

I may be missing your intention, but I do not understand the need to clone a second copy of the repo to another folder and then symlink files back and forth between the two copies. If (given my explanation above) you still feel it has merit I'd like to understand.
 
> > test my changes, ex: run the new app,
> 
> Can you elaborate on this? You're saying just invoke main.sh from the git repo itself?

Yes. If you're using the method I described, you can just run `ds` like normal and your newly added app will appear in the menu, or you can run `ds -a <new_app>` etc. If you're making changes to the shell scripts, it's usually a good idea to test that those changes do what you expect. I did start making test functions at the bottom of each file and an automated way for GHA checks to run those test functions, but most of what the functions do currently is make sure the top function in the file completes running with a `0` exit code. Those functions could be greatly expanded into more reliable unit tests in many cases (I'm not sure how it would work with the menus, but almost everything else could probably be more thorough). I don't need that done anytime soon (or I would have put more effort into it by now 😄 ). Anyway, as far as documentation of contributing goes, the idea would be to ensure that whatever you change (new app, shell scripts, modifying an existing app, etc) is tested locally before you open a PR.

2022-06-30 03:27 UTC, shahvirb commented on .github/CONTRIBUTING.md
> +You should now have an environment where the DockSTARTer GUI and CLI use files you are editing in your local git repository. Eg. if you add a new app into `/path/to/your/ds-repo/compose/.apps` you sh
Ahh ok this makes perfect sense. I should have read into main.sh. I see some of that logic now.

Well in that case all of this can be reduced to cloning your dev repo and then `bash /path/to/your-ds-repo/main.sh` followed by your usual ds commands.

I will clean up this section. Thank you!

2022-06-30 17:52 UTC, shahvirb commented on .github/CONTRIBUTING.md
> +You should now have an environment where the DockSTARTer GUI and CLI use files you are editing in your local git repository. Eg. if you add a new app into `/path/to/your/ds-repo/compose/.apps` you sh
Done: 
https://github.com/GhostWriters/DockSTARTer/pull/1491/commits/23db51ded1cce329087f945b848ca6ad729679e2

2022-06-30 18:01 UTC, nemchik approved these changes
LGTM, thanks!

2022-06-30 18:09 UTC, merged