Added support for TRANSMISSION_WEB_HOME environment variable
GhostWriters/DockSTARTer pull request #1535
Opened 2022-09-16 04:54 UTC by marcellus00

# Pull request

**Purpose**
Linuxcontainer transmission image contains a few alternative web ui's, however it was impossible to set an environment variable TRANSMISSION_WEB_HOME to use them

**Approach**
Simple fix by adding TRANSMISSION_WEB_HOME to transmission[vpn][.lables].yml files

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**

**Requirements**

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2022-09-17 16:31 UTC, shahvirb commented on compose/.apps/transmissionvpn/transmissionvpn.yml
> +      - TRANSMISSION_WEB_HOME=${TRANSMISSIONVPN_WEB_HOME}
Does this image support this variable? Did you do a functional test?

2022-09-17 16:31 UTC, shahvirb commented on compose/.apps/transmission/transmission.labels.yml
> +      com.dockstarter.appvars.transmission_web_home: ""
What happens when this variable is blank? Does the app default to the standard UI?

2022-09-18 16:56 UTC, nemchik commented on compose/.apps/transmissionvpn/transmissionvpn.yml
> +      - TRANSMISSION_WEB_HOME=${TRANSMISSIONVPN_WEB_HOME}
These variables are not specific to the image, they are supported by Transmission. https://github.com/transmission/transmission/blob/main/docs/Environment-Variables.md

This would be a correct implementation.

2022-09-18 16:59 UTC, nemchik requested changes
I'm OK with these changes, but I would like to also see information added to the documentation files (in the docs folder) explaining what you might set these variables to. I believe at some point in the past, binhex's transmissionvpn image included alternate transmission web UIs, so it might have been possible to use this variable to access them. I don't believe the lsio transmission image has ever included alternate UIs, so it would be good to know how to use the variable. My guess is you need to download the alternate web UI separately, put it in your config folder (or somewhere the container can see) and use a path like `/config/ui/alt` or something.

2023-01-24 00:07 UTC, closed without merging