Add pgAdmin and pgBackup
GhostWriters/DockSTARTer pull request #1692
Opened 2023-11-09 23:39 UTC by smilerz

# Pull request

**Purpose**
Added pgAdmin and pgBackup containers.
Updated Postgres documentation referencing these containers.
Added Postgres documentation with example of common command line operations.

 - [x] Created all app specific yml files.
 - [x] Created pgadmin and pgbackup documentation files.
 - [x] Add links to documentation in mkdocs.yml.
 - [x] Tested adding and removing app with command line.
 - [x] Tested adding and removing app with GUI.

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2023-11-11 00:43 UTC, angrycuban13 requested changes

2023-11-12 22:54 UTC, smilerz commented on compose/.apps/pgadmin/pgadmin.yml
> +      - PGADMIN_LISTEN_PORT=5050
There are no external ports for pgbackup, if I understand correctly, this is just used a docker health check since the container is really nothing more than a cron schedule.

The container example documentation has this set, though it has a default and I don't really understand what use case would require changing it.  I'm happy to take it out.

2023-11-12 22:55 UTC, smilerz commented on compose/.apps/pgbackup/pgbackup.labels.yml
> +      com.dockstarter.appvars.pgbackup_postgres_password: ""
Can that be done in the defaults on labels?  Or do you just leave them out here and pass the postgres variables in the yml?

2023-11-12 23:57 UTC, nemchik commented on compose/.apps/pgadmin/pgadmin.yml
> +      - PGADMIN_LISTEN_PORT=5050
Removing it would probably be best for now.

2023-11-12 23:57 UTC, nemchik commented on compose/.apps/pgbackup/pgbackup.labels.yml
> +      com.dockstarter.appvars.pgbackup_postgres_password: ""
> What we've done in the past is setting this to the Postgres user/pass variable

don't cross variables between containers. i've tried to reduce that as much as possible. if we're setting the same default value for both that's fine. blank is probably also fine in this case.

2023-11-22 21:21 UTC, nemchik approved these changes

2023-11-22 21:21 UTC, merged