Make DockStarter work with CoreOS (immutable filesystem, no traditional package manager)
GhostWriters/DockSTARTer pull request #1731
Opened 2024-02-20 19:35 UTC by dylanmtaylor

# Pull request

**Purpose**
Closes #1730. 

Tested on [ucore-hci from the Universal Blue project](https://github.com/ublue-os/ucore). Manual workaround needed for docker compose plugin:
```
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
```
I also set SELinux to permissive. After that, it worked perfectly and all my containers spun up. :-)
![image](https://github.com/GhostWriters/DockSTARTer/assets/277927/ed2b9d76-8bdd-4cc8-81fb-6344418c8774)

**Approach**
How does this change address the problem?
* Uses $HOME/bin instead of /usr for the filesystem
* Doesn't fail hard if it detects no supported package manager, instead checking if the commands we need are there.

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [x] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2024-02-21 00:42 UTC, nemchik requested changes

2024-02-21 00:42 UTC, nemchik commented on .scripts/package_manager_run.sh
> +        # We might not need a supported package manager at all if the dependencies are there already. Let's validate that.
This whole section (all the changes in this file) might not work as this script is called multiple times sequentially by other scripts, such as here:
https://github.com/GhostWriters/DockSTARTer/blob/55fdbccd2d1549d44996115d7aca5971fe901ce6/.scripts/update_system.sh#L6-L9

It might work if we nest an additional `if` inside this `else` to check the `${ACTION}` and only act when it's called with `install` (most of the deps you have below) or `install_docker` (special handling to check for `docker` and the `docker compose` v2 plugin).

2024-02-21 00:42 UTC, nemchik commented on .scripts/symlink_ds.sh
> +    if findmnt -n /usr | grep "ro"; then
This is a clever approach, but I wonder if we can set a variable along the lines of `DS_SYMLINK_TARGET` with a default value of `/usr/local/bin/ds` and then change the value to `$HOME/bin/ds` if `/usr` is not writeable, and then let the rest of the logic be the same for both cases. There's also handling for `/usr/bin/ds` in the existing code, and I believe the original need for handling `/usr/bin/ds` vs `/usr/local/bin/ds` is which one is on path for different OS, so it could even be worth checking the path variable to see which one we need, or if we have to warn the user to adjust their path.

2024-02-21 02:16 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        commands=("curl" "docker" "docker-compose" "git" "grep" "sed" "whiptail")
I'll remove the check for it then.

2024-02-21 02:22 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        # We might not need a supported package manager at all if the dependencies are there already. Let's validate that.
I have tested this and in practice, it works and there is no noticeable latency with other commands, but in the interest of it being fully correct I can add that condition

2024-02-21 02:29 UTC, dylanmtaylor commented on .scripts/symlink_ds.sh
> +    if findmnt -n /usr | grep "ro"; then
Hmm, I suppose we can do something with that path variable. This is what mine looks like as an example.

$ echo $PATH
/var/home/dylan/.local/bin:/var/home/dylan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

Notably, all of the possible paths are on it. I'll try to do a check to decide if we want to print that message.

2024-02-21 02:37 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        echo "All commands are available."
I removed these lines as it felt unnecessarily verbose.

2024-02-21 03:17 UTC, nemchik requested changes

2024-02-21 03:17 UTC, nemchik commented on .scripts/package_manager_run.sh
> +    elif [[ ${ACTION} == "install" ]]; then
This also needs to handle `install_docker` as an `ACTION` which is specific to ensuring `docker` and `docker compose` are available.

2024-02-21 03:17 UTC, nemchik commented on .scripts/package_manager_run.sh
> +        commands=("curl" "docker" "git" "grep" "sed" "whiptail")
Check for docker separately with the `install_docker` action.

2024-02-21 03:17 UTC, nemchik commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
would this work with `if ! docker compose version > /dev/null 2>&1; then` ?

2024-02-21 03:17 UTC, nemchik commented on .scripts/symlink_ds.sh
> +    for target in "${ds_symlink_targets[@]}"; do
This is nearly perfect! But let's stick to uppercase variable naming, and single/plural similarities. ex: `DS_SYMLINK_TARGETS` (for the array) and `DS_SYMLINK_TARGET` (for the iteration inside the loop) just in case there's some other `target` variable in the environment that could conflict.

2024-02-21 03:17 UTC, nemchik commented on .scripts/symlink_ds.sh
> +            sudo rm -f "${target}" || fatal "Failed to remove file. Failing command: sudo rm -f \"${target}\""
```suggestion
            sudo rm -f "${target}" || fatal "Failed to remove file.\nFailing command: ${F[C]}sudo rm -f \"${target}\""
```
Keep the newline and color variable

2024-02-21 03:17 UTC, nemchik commented on .scripts/symlink_ds.sh
> +            sudo ln -s -T "${SCRIPTNAME}" "${target}" || fatal "Failed to create symlink. Failing command: sudo ln -s -T \"${SCRIPTNAME}\" \"${target}\""
```suggestion
            sudo ln -s -T "${SCRIPTNAME}" "${target}" || fatal "Failed to create symlink.\nFailing command: ${F[C]}sudo ln -s -T \"${SCRIPTNAME}\" \"${target}\""
```
Keep the newline and color variable

2024-02-21 03:17 UTC, nemchik commented on .scripts/symlink_ds.sh
> +        ds_symlink_targets=("HOME/bin")
Does this need a `$` ?

2024-02-21 03:18 UTC, dylanmtaylor commented on .scripts/symlink_ds.sh
> +        ds_symlink_targets=("HOME/bin")
Yes, great catch!

2024-02-21 03:20 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
Maybe. I think the question is dependent on the return value being 0 or 1.

2024-02-21 03:27 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
I'm not sure, so don't want to change this right now.

2024-02-21 04:28 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
```
dylan@Dylan-PowerEdge-R730:~$ docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'
dylan@Dylan-PowerEdge-R730:~$ echo $?
1
```

Decided to try this after all. Doesn't break things that are already running to mess up compose.

2024-02-21 04:29 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
$ if ! docker compose version > /dev/null 2>&1; then echo "fail"; fi
fail

I think we can do it that way.

2024-02-21 04:30 UTC, dylanmtaylor commented on .scripts/package_manager_run.sh
> +        if [[ "$(docker compose 2>&1)" == *"docker: 'compose' is not a docker command."* ]]; then
Yes, this should work.
```
dylan@Dylan-PowerEdge-R730:~$ docker compose version
Docker Compose version v2.24.5
dylan@Dylan-PowerEdge-R730:~$ echo $?
0
dylan@Dylan-PowerEdge-R730:~$ if ! docker compose version > /dev/null 2>&1; then echo "fail"; fi
```

2024-02-23 00:43 UTC, nemchik commented
Changing branch and merging so I can stage in some additional adjustments.

2024-02-23 00:43 UTC, merged