Update env_update.sh
GhostWriters/DockSTARTer pull request #1745
Opened 2024-03-20 07:49 UTC by CLHatch

Add headings for each app in the .env in the form of:

#
# APPNAME
#

# Pull request

**Purpose**
Describe the problem or feature in addition to a link to the issues.

**Approach**
How does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
Describe the research stage
Links to blog posts, patterns, libraries or addons used to solve this problem

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2024-04-06 19:08 UTC, nemchik requested changes

2024-04-06 19:46 UTC, CLHatch commented on .scripts/appvars_create.sh
> +    APP_VAR_SEARCH=$(
It seems that would work, since there are no spaces in what we are searching for.

2024-04-06 19:48 UTC, CLHatch commented on .scripts/env_update.sh
> +inArray() {
I was likely going to get rid of `inArray()` anyways, since I discovered the inline search using `=~`.  I'll likely change it to using the method in that link.

2024-04-07 02:44 UTC, CLHatch commented on .scripts/appvars_create.sh
> +        for line in "${APP_LABEL_LINES[@]}"; do
The `{}` in this case are actually just because the `APP_LABEL_LINES` array is a temporary array, I made it local to that block.  The `return` doesn't break out of the that block, it breaks out of the entire function if it finds there are no labels for the application.

2024-04-07 07:18 UTC, CLHatch commented
Pretty sure those comments have all been addressed.

2024-09-07 19:42 UTC, nemchik commented
I realize I had pending review comments. I might not have fully finished the review, but I'm going to call it good on most of this if you can address the few comments I left.

2024-09-07 21:16 UTC, CLHatch commented on .scripts/appvars_create.sh
> +                # shellcheck disable=SC2199
There some weirdness going on here that the recommended usage of  `[*]` didn't work but the warned about usage of `[@]` did work. Finally resorted to disabling the warning and using the code that worked. :D

2024-09-07 22:01 UTC, CLHatch commented on .scripts/appvars_create.sh
> +    local APPTEMPLATES="${APPSFOLDER}/${FILENAME}"
I forget if it was used elsewhere at some point or not.  Possibly I made it a variable in case I did re-use it?  I can easily remove the variable.

2024-09-07 22:34 UTC, nemchik approved these changes

2024-09-07 22:40 UTC, merged