Fix prometheus app data and config volumes
GhostWriters/DockSTARTer pull request #1778
Opened 2024-08-20 16:45 UTC by giannoug

# Pull request

**Purpose**
Propose a fix for properly mounting volumes for data and config in the prometheus app ([issue 1777](https://github.com/GhostWriters/DockSTARTer/issues/1777))

**Approach**
Mount configuration to a prometheus folder in `DOCKERCONFDIR`. Data is mounted in a prometheus folder in `DOCKERSTORAGEDIR`.

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CODE_OF_CONDUCT.md).

2024-08-20 17:44 UTC, nemchik requested changes

2024-08-20 17:44 UTC, nemchik commented on compose/.apps/prometheus/prometheus.yml
> +      - ${DOCKERSTORAGEDIR}/prometheus:/prometheus
```suggestion
      - ${DOCKERCONFDIR}/prometheus/etc:/etc/prometheus
      - ${DOCKERCONFDIR}/prometheus/data:/prometheus
```

Just using https://prometheus.io/docs/prometheus/latest/installation/#using-docker and https://github.com/selfhosters/unRAID-CA-templates/blob/cf265bcdcde5f6224098c183e2f69be734b9a898/templates/prometheus.xml#L16-L17 as a reference, I don't think the data from prometheus would be considered mass storage. Since the volumes were incorrect previously, I don't consider this a breaking change (it's a fixing change lol).

2024-08-20 23:49 UTC, giannoug commented on compose/.apps/prometheus/prometheus.yml
> +      - ${DOCKERSTORAGEDIR}/prometheus:/prometheus
No strong opinion since I'm not that familiar with DockSTARTer, but it makes sense. Updated my PR!

2024-08-21 22:53 UTC, nemchik approved these changes

2024-08-21 22:55 UTC, merged